apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io
    targetRevision: 9.8.3
    chart: gitlab
    helm:
      valuesObject:
        gitlab:
          toolbox:
            enabled: false
          webservice:
            ingress:
              tls:
                secretName: gitlab-webservice-ingress-tls
            hpa:
              minReplicas: 1
              maxReplicas: 1
          gitlab-shell:
            minReplicas: 1
            maxReplicas: 1
          gitaly:
            persistence:
              size: 3Gi
          sidekiq:
            minReplicas: 1
            maxReplicas: 1
        global:
          appConfig:
            lfs:
              enabled: false
            artifacts:
              enabled: false
            uploads:
              enabled: false
            packages:
              enabled: false
          psql:
            host: postgres-cluster
            database: gitlab
            username: postgres
            password:
              secret: postgres.postgres-cluster.credentials.postgresql.acid.zalan.do
              key: password
          kas:
            enabled: false
          minio:
            enabled: false
          hosts:
            domain: cluster-1.example.com
          ingress:
            tls:
              enabled: true
              external: true
            configureCertmanager: false
            class: traefik
            annotations:
              cert-manager.io/cluster-issuer: my-ca-issuer
        installCertmanager: false
        prometheus:
          install: false
        postgresql:
          install: false
        nginx-ingress:
          enabled: false
        upgradeCheck:
          enabled: false
        registry:
          enabled: false
        redis:
          master:
            persistence:
              size: 1Gi
        gitlab-runner:
          certsSecretName: gitlab-tls-cert-for-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
