apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: victoriametrics-agents
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          # Template values that will be passed to each cluster
          cluster_url: "{{server}}"
          cluster_name: "{{name}}"
      selector:
        matchExpressions:
          - key: cluster-name # Assuming your cluster secrets have a 'cluster-name' label
            operator: NotIn
            values:
              - cluster-1
  template:
    metadata:
      name: "vm-{{cluster_name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://victoriametrics.github.io/helm-charts/
        targetRevision: 0.70.0
        chart: victoria-metrics-k8s-stack
        helm:
          valuesObject:
            vmsingle:
              enabled: false
            vmalert:
              enabled: false
            alertmanager:
              enabled: false
            grafana:
              enabled: false
            vmagent:
              additionalRemoteWrites:
                - url: https://vmagent.{{cluster_name}}.example.com/api/v1/write
              spec:
                host_aliases:
                  - ip: "192.168.193.1"
                    hostnames:
                      - "vmagent.{{cluster_name}}.example.com"
                secrets:
                  - central-vmagetnt-tls-ca
                extraArgs:
                  remoteWrite.tlsCAFile: /etc/vm/secrets/central-vmagetnt-tls-ca/cluster-1-ca.crt
                externalLabels:
                  cluster: "{{cluster_name}}"
              ingress:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: my-ca-issuer
                ingressClassName: "traefik"
                hosts:
                  - vmagent.{{cluster_name}}.example.com
                tls:
                  - secretName: vmagent-ingress-tls
                    hosts:
                      - vmagent.{{cluster_name}}.example.com
      destination:
        server: "{{cluster_url}}"
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged # for node-exporter daemonset
